for i in range(1):
    for i in range(1):
        for i in range(1):
            for i in range(1):
                for i in range(1):
                    for i in range(1):
                        for i in range(1):
                            for i in range(1):
                                for i in range(1):
                                    for i in range(1):
                                        for i in range(1):
                                            for i in range(1):
                                                for i in range(1):
                                                    for i in range(1):
                                                        for i in range(1):
                                                            for i in range(1):
                                                                for i in range(1):
                                                                    for i in range(1):
                                                                        for i in range(1):
                                                                            for i in range(1):
                                                                                pass
